<?php
/**
 * Created by PhpStorm.
 * User: Liam
 * Date: 9/16/2019
 * Time: 10:23 AM
 */

require_once("Pokemon.php");

class Pidgey extends Pokemon implements Iflyer{


    protected $isFlying;
    protected $speed;
    protected $direction;

    public function __construct($weight, $HP, $lat, $long)
    {
        parent::__construct('Pidgey', "pidgey.png", $weight, $HP, $lat, $long, 'flying');
        //$this->speed = $speed;
        //$this->isFlying = $isFlying;
        //$this->direction = $direction;
    }

    function attack(Pokemon $target)
    {
        //echo "Bulbasaur is Vine Whipping<br>";
        $target->HP = $target->HP - $this->getDamage();
    }


    function getDamage()
    {
        return $this->getWeight()*0.4;
    }

    function takeOff()
    {
        // TODO: Implement takeOff() method.
    }

    function land()
    {
        // TODO: Implement land() method.
    }

    function getFlying()
    {
        return $this->isFlying;
    }

    function getSpeed()
    {
        return $this->speed;
    }

    function getDirection()
    {
        return $this->direction;
    }

    function setLatitude($lat)
    {
        parent::setLatitude($lat); // TODO: Change the autogenerated stub
    }

    function setLongitude($long)
    {
        parent::setLongitude($long); // TODO: Change the autogenerated stub
    }

    function getLatitude()
    {
        return parent::getLatitude(); // TODO: Change the autogenerated stub
    }

    function getLongitude()
    {
        return parent::getLongitude(); // TODO: Change the autogenerated stub
    }


}